### ISSUE TITLE
Theme broken in latest Hyper update

### ISSUE THREAD

**Issue by wadehammes** [carloscuesta/hyper-materialshell#10]
Hello @carloscuesta

Latest Hyper version, 1.3.2, breaks this theme (lost cursor and weird flashing color):
![may-10-2017 11-05-46](https://cloud.githubusercontent.com/assets/222170/25906035/9dd7fa3c-3571-11e7-825c-6729764842f7.gif)

Determined it was this plugin by deactivating all I had running, and turning on one by one...this one caused the issue (vanilla Hyper experiences none of these issues).

MacOS 10.12.4
Hyper 1.3.2

**Comment by carloscuesta** [comment]
Thanks for reporting this issue @wadehammes I'm taking a look into it, (happens to me aswell)

**Comment by carloscuesta** [comment]
It's fixed for me at the latest version (1.3.3) can you take a look @wadehammes

**Comment by wadehammes** [comment]
@carloscuesta looks good! Closing this out.
