### ISSUE TITLE
Do not override cursorShape

### ISSUE THREAD

**Issue by ricardocosta89** [carloscuesta/hyper-materialshell#16]
Hello @carloscuesta

First of all, great work with this theme!

I've been trying to customize the prompt to my taste with one of the oh-my-zsh themes and the only thing missing is the cursor shape. It seems that `hyper-materialshell` is overriding the `.hyper.js` configuration. https://github.com/carloscuesta/hyper-materialshell/blob/master/index.js#L20

Would you be willing to not do that? Since this theme is mostly changing colors, it seems weird to be forcing the users to `UNDERLINE` cursor instead of using the configuration.

Thanks!

**Comment by carloscuesta** [comment]
Hey @ricardocosta89!

I think it makes sense, so I'm removing it

**Comment by ricardocosta89** [comment]
Thanks!
