### ISSUE TITLE
Font size and family should not get overridden

### ISSUE THREAD

**Issue by alireza-ahmadi** [carloscuesta/hyper-materialshell#5]
Hello @carloscuesta
Thanks for your lovely work! Just a minor problem: Current version of the theme overrides font-size and font-family which is a little bit annoying because I have weak eyesight that forces me to use larger font size, also this problem prevent users from using different fonts, such as Fira or Hack.

Do you overridden the font size intentionally or it's just a bug and I can submit a pull request for fixing that?

**Comment by carloscuesta** [comment]
Hey @alireza-ahmadi it's overrided intentionally but your comment makes sense, so feel free to send a pull request to prevent overriding font-size and family 👍 

Then I will add something like the font used to the README, incase someone wants to have the exact look as the screenshot.
