### ISSUE TITLE
Ocenanic version

### ISSUE THREAD

**Issue by nico29** [carloscuesta/hyper-materialshell#7]
Hello @carloscuesta

First things first, great work !

Then, quick question, do you plan on making the oceanic version of the theme, like you did for [iTerm](https://github.com/carloscuesta/materialshell/blob/master/osx/iterm/materialshell-ocean.itermcolors) ❓ 
Thank you 😸

**Comment by carloscuesta** [comment]
Hey @nico29 thanks for submitting an issue!

Really never thinked about it, but could be great to have an oceanic version of materialshell for HyperTerm 😄

**Comment by nico29** [comment]
Are [those colors](https://github.com/carloscuesta/materialshell/blob/master/colors.md) (oceanic) the one to use ?

**Comment by carloscuesta** [comment]
Just released and published it thanks again @nico29 🎉 

https://github.com/carloscuesta/hyper-materialshell/releases/tag/v1.4.0
